# -*- coding: utf-8 -*-
"""
Created on Thu Sep  7 19:07:16 2017

@author: Spencersun
"""

import random

List = [0,1,2,3,4,5,6,7,8,9]
pick_number = random.sample(List, 1)
print ("Suppose the digit generated by program is %s"% pick_number[0])
input_number = int(input("Guess the digit:"))
if input_number>pick_number[0]:
    print ("Your answer is high than required")
if input_number<pick_number[0]:
    print ("Your answer is low than required")
if input_number==pick_number[0]:
    print ("Your answer is PERFECT!! Congratulations!!")